export const DEFAULT_KIT_ITEMS = [
  { name: "Conjunto placa microbit", quantity: 1 },
  { name: "Shield", quantity: 1 },
  { name: "Bateria de 3,7V da Shield", quantity: 1 },
  { name: "Carregador de pilhas", quantity: 1 },
  { name: "Pilhas recarregáveis", quantity: 1 },
  { name: "Multímetro", quantity: 1 },
  { name: "Servo motor", quantity: 3 },
  { name: "Motor com caixa de redução", quantity: 2 },
  { name: "Rodas para motor", quantity: 2 },
  { name: "Tela I2C LCD", quantity: 1 },
  { name: "Sensor ultrassônico", quantity: 1 },
  { name: "Sensor PIR", quantity: 1 },
  { name: "Sensor de temperatura e umidade", quantity: 1 },
  { name: "Sensor de luz ambiente", quantity: 1 },
  { name: "Sensor de umidade do solo", quantity: 1 },
  { name: "Sensor seguidor de linha", quantity: 2 },
  { name: "Módulo relé digital", quantity: 1 },
  { name: "Potenciômetro", quantity: 1 },
  { name: "Cabo 4 pinos F/F conversão para conector groove", quantity: 1 },
  { name: "Cabo analogico conector engate rapido 3 vias", quantity: 1 },
  { name: "Cabo jumper fêmea/fêmea", quantity: 1 },
  { name: "Cabo jacaré", quantity: 1 },
  { name: "Caixa plastica", quantity: 1 },
];
